#server:
#  address: 0.0.0.0
#  port: 8080

spring:
  # konfigurasi untuk koneksi db
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

    # sesuaikan nama database anda dengan di bawah ini
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    # sesuaikan dengan NAMA dan PASSWORD anda dengan username password di bawah ini
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: spring-blog

  sql:
    init:
      mode: always